### ISSUE TITLE
Oscam info log screen does not scroll up/down

### ISSUE THREAD

**Issue by margy82** [OpenViX/enigma2#1]
As the title, in log screen there is not the possibility to scroll up/down

Thanks

**Comment by RobvanderDoes** [comment]
This issue is still present today.

**Comment by AbuBaniaz** [comment]
I have gone back to Jun 23, 2011 version, issue is still there. Can't go back any further as it crashes

**Comment by RobvanderDoes** [comment]
Why did you close this?
As far as I know, this hadn't been fixed.

**Comment by RobvanderDoes** [comment]
Not specifically, butbon dev 5. 2. 022.001 OscamInfo crashes.
I was not aware of a commit in this area; on previous dev build it was still fine, and had the not scroll issue.

**Comment by original-birdman** [comment]
See thread:
https://www.world-of-satellite.com/showthread.php?60495-oscam-info-card-reader-information-crashes&p=479437#post479437
since having information about the same issue in two places seems to be causing an issue.
