### ISSUE TITLE
Boot crash in OpenVix 6.6.2

### ISSUE THREAD

**Issue by scan-line** [OpenViX/enigma2#1046]
I use OpenVix on a Vu+ Solo2 for TivuSat, with a CAM and TivuSat gold card. This has been working well for many years. For some months I have failed to make a clean flash of latest OpenVix - it crashes during boot. I have now been able to investigate and would like to share both what I have found - and a possible solution.

Problem version: 6.6.2
Last known good version: 6.4.11

After a clean flash from USB, OpenVix crashes during startup. With the CAM removed, OpenVix starts up just fine (which thankfully allowed me to ftp access to the crash logs). Here’s the critical part of a crash log, with my interpretation below.

```
<    56.552308> 21:49:08.2914 [StartEnigma]  Initialising RecordingConfig.
<    56.576873> 21:49:08.3160 [StartEnigma]  Initialising UsageConfig.
<    56.580625> 21:49:08.3197 [eDVBDB] Renumbering...
<    56.618217> 21:49:08.3573 [eTuxttxtApp] enable caching
<    56.672929> 21:49:08.4120 [CI0 SESS] slot: 0x86f6b8
<    56.673052> 21:49:08.4124 [CI0 AM] application info:
<    56.673352> 21:49:08.4124 [CI0 AM]   len: 13
<    56.673394> 21:49:08.4125 [CI0 AM]   application_type: 1
<    56.673435> 21:49:08.4125 [CI0 AM]   application_manufacturer: 00 00
<    56.673473> 21:49:08.4126 [CI0 AM]   manufacturer_code: 00 00
[CI0 AM]   menu string: TivùSat
<    56.673631> 21:49:08.4127 PC: 76c53504
<    56.673715> 21:49:08.4128     00000000 00000001 00000000 744868c0
<    56.673765> 21:49:08.4129     ffff8004 008ea7c0 00000000 00000001
<    56.673807> 21:49:08.4129     76b41e2c 00000080 000000e0 f9766954
<    56.673851> 21:49:08.4129     74482a08 77bbe000 74207910 00481040
<    56.673895> 21:49:08.4130     00000000 0000001c 00000001 00000001
<    56.673941> 21:49:08.4130     74207938 00000007 7420793f 00639c84
<    56.673982> 21:49:08.4131     0000006c 76475380 00000001 00000000
<    56.674091> 21:49:08.4132     770041e0 74482908 74482a78 76c534fc
<    56.674219> 21:49:08.4133 [EPGC Load] Poller disabled.
<    56.674715> 21:49:08.4138 [EPGC Save] Poller disabled.
<    56.674737> 21:49:08.4138 Backtrace:
<    56.675573> 21:49:08.4147 /usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x474494]
<    56.675893> 21:49:08.4150 /usr/lib/libpython3.12.so.1.0(n/a) [0x76C53504]
<    56.675979> 21:49:08.4151 -------FATAL SIGNAL (11)

```
Looking at the log bytes, the accented u in TivùSat (read from the card) is a latin-1 accented-u, not a utf-8 accented-u.

Reading the source

https://github.com/OpenViX/enigma2/blob/278c4c85650580e8f90662c947ed9d63dc69bf5f/lib/dvb_ci/dvbci_appmgr.cpp#L48-L58

suggests that the crash is triggered between line 50 (logging the TivuSat string) and line 57 (logging the TivSat string (no u) after repairing to utf-8). From the file history, the repair code and associated logging was added 6-7 months ago.

I have tried comparing the enigma2 source with other distributions, to see if a fix ls already known. I think it is, and will use OpenATV as an example. There is a recent commit that (a) logs problem bytes more cautiously, as hex; (b) repairs to utf8 by converting from latin-1. This also does a better job of repairing the TivuSat string in my case.
 
https://github.com/openatv/enigma2/blob/f94f5ead12035b8a5e8556533f0ab6dddab1ac0e/lib/dvb_ci/dvbci_appmgr.cpp#L50-L54

I have temporarily flashed openatv 7.3 (2024 06 25), to see how this behaves. My box starts fine with the CAM in place, and shows the correct TivùSat string in the CI menus.

**Comment by TwolDE2** [comment]
Thanks for all the info….. will look into it.

**Comment by TwolDE2** [comment]
@scan-line ……added can you confirm OK with your card(s)

**Comment by Huevos** [comment]
Will be in 6.6.004.

**Comment by scan-line** [comment]
Super - will test and confirm when the 6.6.004 image ships.

**Comment by scan-line** [comment]
Tested in 6.6.004. Boot completes successfully (with card inserted).
