### ISSUE TITLE
Cannot use gdb on enigma threads

### ISSUE THREAD

**Issue by ferrieux** [OpenViX/enigma2#13]
Trying to debug enigma's freezes, I installed gdb:

  opkg install gdb

I also removed the security restriction so that /lib/libthread_db.so.1 is  reachable: 

  echo "set auto-load safe-path /" > .gdbinit

However, whenever I try to attach to enigma, I get the dreadful libthread_db mismatch error:

 warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

Stracing gdb itself shows that /lib/libthread_db.so.1 is properly opened:

 open("/lib/libthread_db.so.1", O_RDONLY|O_CLOEXEC) = 4

So, there truly is some kind of mismatch between the installed versions of libpthread and libthread_db. But since the actual criterion is not obvious, I'm stuck.
Here are the installed versions:

 root@vuultimo:~# opkg search /lib/libpthread.so.0 
 libc6 - 2.19-r0

 root@vuultimo:~# opkg search  /lib/libthread_db.so.1 
 libthread-db1 - 2.19-r0

 root@vuultimo:~# opkg search  /usr/bin/gdb
 gdb - 7.7.1-r0

Any idea how to proceed ? Debugging enigma's deadlocks without this is out of the question...
TIA,

-Alex

**Comment by RobvanderDoes** [comment]
Is this still a current issue?
