### ISSUE TITLE
Trickmode (x8 fwd) freezes in eDVBTSTools::findNextPicture

### ISSUE THREAD

**Issue by ferrieux** [OpenViX/enigma2#14]
On an Ultimo with enigma2 - 3.0+git16208+1b533d9-r19 ,
fast-forwarding 8x on some recorded TS gets the spinner forever.
(note this is not a new regression, I've seen this on the Ultimo for ages)

Investigation with gdb shows that the freeze is made of an infinite loop in eDVBTSTools::findNextPicture in lib/dvb/tstools.cpp.

The stack frame at this point is below. Adding breakpoints at each function entry shows that findNextPicture never returns, while the two deeper levels (findFrame and getStructureEntryNext) return immediately.

Also, looking at the /proc/PID/fdinfo/FD for the TS file shows that the seek position does not change in this state, and is not an extreme value: 41531832 in my case.
#0  0x004cdc18 in eMPEGStreamInformation::getStructureEntryNext(long long&, unsigned long long&, int) ()
#1  0x004e46a4 in eDVBTSTools::findFrame(long long&, unsigned int&, int&, int) ()
#2  0x004e48b0 in eDVBTSTools::findNextPicture(long long&, unsigned int&, int&, int) ()
#3  0x0049265c in eDVBChannel::getNextSourceSpan(long long, unsigned int, long long&, unsigned int&) ()
#4  0x0046a8c8 in eFilePushThread::thread() ()
#5  0x0046d310 in eThread::wrapper(void*) ()

**Comment by RobvanderDoes** [comment]
I don't think this is still a current issue.

**Comment by ferrieux** [comment]
Why ? Do you have a specific commit in mind ?

**Comment by RobvanderDoes** [comment]
Because I can't reproduce it.

**Comment by ferrieux** [comment]
Then may be you can "git bisect" ? (I don't have the build environment)

**Comment by RobvanderDoes** [comment]
> I don't have the build environment

I'm sorry: neither have I.

**Comment by original-birdman** [comment]
> Also, looking at the /proc/PID/fdinfo/FD for the TS file shows that the seek position does not change in this state, and is not an extreme value: 

It won't be looking in the ts file at that point· It will be looking the the ts.sc (?) file, and will have cached the values from there in memory anyway.

> Then maybe you can "git bisect" ? (I don't have the build environment)

A fix was applied in April 2016:

https://github.com/OpenViX/enigma2/commit/33d172b5a3ad1b22d69ce60c2102552537b77929#diff-3322bb09addee770c32973a183686def
