### ISSUE TITLE
Add/Edit timer doesnt work through openwebif

### ISSUE THREAD

**Issue by ffallah** [OpenViX/enigma2#180]
I have OpenViX 5.0.021 installed on my vu+ solo 4k.
I noticed you can not add timers through openwebif, the problem is that Channel list comes completely empty (I have my Favorites bouquet populated).
I added a Timer through TV interface, and then tried to edit it and noticed edit button doesnt work at all.

**Comment by ViX-Sicilian** [comment]
Just test with OpenViX 5.0.023 about to be released and working fine.

**Comment by AbuBaniaz** [comment]
I am closing this issue. If it still exists, please raise the issue on the openwebif repository
