### ISSUE TITLE
'gstBusCall eos event' causing IPTV recording end

### ISSUE THREAD

**Issue by devait** [OpenViX/enigma2#181]
Log file shows:

<189550.363> [eMP3ServiceRecord] gstBusCall eos event
<189550.383> [RecordTimer] activating state 3
<189550.384> [RecordTimer] stop recording
<189550.386> [eMP3ServiceRecord] stop recording

Stream doesn't actually stop when viewing it, but for some reason this happens around the 3hr mark when recording. Any ideas? Can I disable this?

TIA

**Comment by devait** [comment]
Can someone please point me in the right direction to how I can solve this myself i.e. by commenting out the 'gstBusCall eos event' code that stops the recording at 3hrs? I've got the build from https://github.com/oe-alliance/build-enviroment so I know I need to fork the https://github.com/OpenViX/enigma2 repo, just don't know where I need to update the build environment recipies. TIA

**Comment by AbuBaniaz** [comment]
Were you viewing when the recording terminated?

**Comment by devait** [comment]
No, the box was on standby. If I can fork this repo and get the build to use my own repo I can test the change out. I guess the provider is maybe sending this 'gstBusCall eos event' for some reason. I can watch 5 hours straight so ignoring this message won't cause an issue, at least for now...

**Comment by AbuBaniaz** [comment]
There was a thread on the forum, it turns out that the provider was closing off the stream after 180 minutes.

**Comment by devait** [comment]
Which forum please? Is this all providers? It doesn't happen when I watch live, only recording while on standby... TIA

**Comment by AbuBaniaz** [comment]
OpenVix forum.

**Comment by devait** [comment]
Which thread please, I cannot find it. Thanks again.

**Comment by devait** [comment]
Ah yes, that's my personal profile so it's from me! ;)

As I said initially:
Can someone please point me in the right direction to how I can solve this myself i.e. by commenting out the 'gstBusCall eos event' code that stops the recording at 3hrs? I've got the build from https://github.com/oe-alliance/build-enviroment so I know I need to fork the https://github.com/OpenViX/enigma2 repo, just don't know where I need to update the build environment recipies. TIA

**Comment by devait** [comment]
Sorted out the fork and build now. Will let you know if the recordings continue past 180 mins.

**Comment by devait** [comment]
Just found out that providers send the EOS event to stop people leaving their devices on while they sleep!!

So, all I need to do is kick off recording again from receiving this event. I am try a few things in code, will report back on progress...

**Comment by devait** [comment]
My code updates are working and recording the next block after 3hrs ;) I'm seeing if I can move them from the cpp code to RecordTimer.py as that will be better...

**Comment by AbuBaniaz** [comment]
Any update on this?

**Comment by AbuBaniaz** [comment]
Can we close this now?

**Comment by AbuBaniaz** [comment]
@devait 
I have closed this issue. Please re-open if necessary.

Thank you for making the changes
