### ISSUE TITLE
TV Teletext subtitle with background

### ISSUE THREAD

**Issue by kkm** [OpenViX/enigma2#20]
I cant believe this feature is very hard implemented.
![](http://capturei.tikatoy.com/r/13JH.png)
Can someone tell me how can I set this feature?

I am depend of subtitle because I am deaf and this feature is very important for me.
With background color is good readable than text border.

OpenPli, Blackhole, openATV, OpenSpa and VTi doesnt work and nobody can help me.

Thanks for advice.

**Comment by kkm** [comment]
And I did try with skin_user.xml in /etc/engima2 but not working.
![](http://capturei.tikatoy.com/r/DmnI.png)

**Comment by RobvanderDoes** [comment]
We now have a black background in place, that can be switched On/Off; is that sufficient?

**Comment by AbuBaniaz** [comment]
@kkm 
You can press red (quick menu) and switch off the transparency. I hope that works OK for you until the colour feature is added. We have a feature request on the Dev side of the forum.

Also, thanks to @SimonCapewell form 5.3 015, you will be able to long press the subtitle button and toggle the subtitles on/off.
