### ISSUE TITLE
Editing DNS via netwrk menu

### ISSUE THREAD

**Issue by davesayers2014** [OpenViX/enigma2#202]
Hi I have had issues changing DNS on box via network menu if you change the option and set a custom nameserver it doesn't remember the change after a reboot.

Solution Ive used is putty to talnet init 4 to put enigma2 to sleep then edited the resolv.conf file in etc then used init 3 to restart enigma2, editing the file whilst enigma2 is running doesn't save the changes on restart.

So maybe something can be changed within the network menu to be able to save the changes on restart.

Another option ive seen is,

you need to edit a system file, comment out 5 lines towarsd the end of /etc/udhcpc.d/50default

Comment out the following lines (about line 45)
[code]
if [ -x /sbin/resolvconf ]; then
echo -n "$R" | /sbin/resolvconf -a "${interface}.udhcpc"
else
echo -n "$R" > "$RESOLV_CONF"
fi
[/code]

you may need to restart network after. Im not sure what issues it may cause editing 50default
[50default.zip](https://github.com/OpenViX/enigma2/files/1515368/50default.zip)

**Comment by original-birdman** [comment]
This will/may depend on whether you are using DHCP.

**Comment by original-birdman** [comment]
If you're using DHCP (which I presume you are) the place to set your servers is in the DHCP server, surely?

**Comment by davesayers2014** [comment]
Sorry im not sure what you mean by,

> the place to set your servers is in the DHCP server, surely?

I am trying to setup openvpn on enigma2 but it seems Virgin Hub 3 wont use OpenVPN until you set box to google DNS, I have set DHCP to no and I can edit nameserver and changes save on reboot, odd issue I have noticed now is when I restart network with OpenVPN enabled is that I loose internet connection till I disable OpenVPN then network starts then I can re start openvpn but thats a different issue. 

If having DHPC enabled wont allow you to edit DNS, could edit DNS option be disabled if users have DHPC yes?

Ill close this issue and experiment with it. Thanks

**Comment by original-birdman** [comment]
It is possible to configure resolvconf to set up different DNS servers according to which interfaces are active. You'd (might) need to do that if you were running a VPN on the box itself which you bring up and down as required (I had to do this once ...).
But you're not running the VPN on the box - you're running that on your router. So we can ignore that.

If you're running the box using DHCP then you really need to set the DNS server info on the DHCP server, so it gets sent to the clients when they request an IP address.

So the "solutuion" here is to set your box to use a static IP address (_i.e_. one not within the router's DHCP range) and then edit in the DNS server(s) you wish. I see from elsewhere that you've done this.  Good.

> If having DHPC enabled wont allow you to edit DNS, could edit DNS option be disabled if users have DHPC yes?

Sounds a good idea. Thanks for the suggestion.

**Comment by Huevos** [comment]
> Sounds a good idea. Thanks for the suggestion.

Good luck with that. It's not a ConfigElement.

**Comment by davesayers2014** [comment]
> It is possible to configure resolvconf to set up different DNS servers according to which interfaces are active. You'd (might) need to do that if you were running a VPN on the box itself which you bring up and down as required (I had to do this once ...).
But you're not running the VPN on the box - you're running that on your router. So we can ignore that.


Sorry I am using openvpn on box I cant run VPN on router plus I want to switch it on and off. Ill experiment with it as this is going off subject but I do have a thread on WOS

**Comment by original-birdman** [comment]
Hmmm...from the forum posts I'd assumed that the VPN was running on the router.

If it's actually running on the Vix box and you want to be able to stop and start it there then you need to configure resolvconf (by hand...).
A VPN will stop/start a tup device, so you add the DNS server you want into that device config. It's several years since I had to do this....

**Comment by original-birdman** [comment]
> Good luck with that. It's not a ConfigElement.

Editing DNS is accessed via the Blue button, so hopefully I just have to disable that iff DHCP is active.

**Comment by Huevos** [comment]
??? 

menu > Setup > Network > Nameserver settings
