### ISSUE TITLE
VU+ Solo2, Openvix 5.1.020, IPTV, No subtitles showing up after selecting sub language

### ISSUE THREAD

**Issue by borzag** [OpenViX/enigma2#238]
It have never worked for me and i first installed version 5.1.013. 
Mostly no subtitles are shown. Sometimes pixeled subtitles appear for a random sentence, in next sentence they are gone. Have also noticed that on some channels, incorrect language are shown.
Would appreciate if someone would like to look in to it. Thanks
![15214916452174518174652813321411](https://user-images.githubusercontent.com/30691105/37620668-2c9f9120-2bbd-11e8-9e26-172b57a15eef.jpg)

**Comment by grisko** [comment]
> It have never worked for me and i first installed version 5.1.013.
> Mostly no subtitles are shown. Sometimes pixeled subtitles appear for a random sentence, in next sentence they are gone. Have also noticed that on some channels, incorrect language are shown.
> Would appreciate if someone would like to look in to it. Thanks
> ![15214916452174518174652813321411](https://user-images.githubusercontent.com/30691105/37620668-2c9f9120-2bbd-11e8-9e26-172b57a15eef.jpg)


Having these problems too on VU+ DUO .. DVB-subtitles is really bad on IPTV.

Danish is really bad .. almost no lines show up .. and the streams with subs work fine in VLC.

I know it's a old box .. but subtitles should work perfect.

Hope someone will help getting this fixed !?

Best Regards
