### ISSUE TITLE
EPG Slow to preview

### ISSUE THREAD

**Issue by attewell** [OpenViX/enigma2#247]
![img_1009](https://user-images.githubusercontent.com/11217684/38015435-3da75b08-32c8-11e8-8fe5-3c9740d8f052.jpeg)
EPG slow to show.. this shows for 1 second before EPG data displays..

**Comment by Huevos** [comment]
And you think one second to parse all that data is a long time?

**Comment by attewell** [comment]
Yes. when my solo2 did it instantly.


unless sol2 has better memory access than mutant




Get Outlook for Android







On Wed, Mar 28, 2018 at 9:05 PM +1300, "Huevos" <notifications@github.com> wrote:












And you think one second to parse all that data is a long time?

**Comment by AbuBaniaz** [comment]
This has been fixed here:
https://github.com/OpenViX/enigma2/commit/01ebdacbd997c93f570b793fd1218fe0c2029e2c

You will have to wait for next Release image
