### ISSUE TITLE
Trashcan location

### ISSUE THREAD

**Issue by EMJB** [OpenViX/enigma2#279]
Some time ago I reported on the forum that there appears to a problem with the trashcan when the "config.usage.default_path" is changed - see https://www.world-of-satellite.com/showthread.php?56402-Trashcan-Location&p=472687. This appears to be due to "movie" being hard-coded into "getTrashFolder" in Trashcan.py (see last post in the above).

I am having problems understanding the logic here, as MovieList.py seems to expect the trashcan to be in  "config.usage.default_path", but the present TrashCan.py logic can put it elsewhere in some circumstances, notably when that path does not include "movie". I have tried using the following code:

> def getTrashFolder(path=None):
	# Returns trash folder without symlinks
	try:
		if path is None or os.path.realpath(path) == '/media/autofs':
			print 'path is none'
			return ""
		else:
			if config.usage.default_path.value in path:
				mountpoint = Harddisk.findMountPoint(os.path.realpath(path))
				trashcan = os.path.join(mountpoint, config.usage.default_path.value)
			else:
				trashcan = Harddisk.findMountPoint(os.path.realpath(path))
			return os.path.realpath(os.path.join(trashcan, ".Trash"))
	except:
		return None

> 

which seems to work for my situation (i.e. config.usage.default_path = /media/hdd/Recs/).

EMJB

**Comment by SimonCapewell** [comment]
Thanks for this. The trashcan being in the root has been bugging me for ages. I don't have *movies* directory, mine's called *TV*, so the trashcan wanted to be up a level and was difficult to find.

**Comment by RobvanderDoes** [comment]
Has this been fixed (by https://github.com/openvix/enigma2/commit/927e841704ddacabbac056183f0d73eac77680e7 )?

**Comment by SimonCapewell** [comment]
Yes

**Comment by RobvanderDoes** [comment]
Closed as fixed by https://github.com/OpenViX/enigma2/commit/927e841704ddacabbac056183f0d73eac77680e7
