### ISSUE TITLE
Crash on opening plugin 'MovieManager

### ISSUE THREAD

**Issue by RobvanderDoes** [OpenViX/enigma2#284]
When trying to open the plugin 'MovieManager' (available on the feeds) E2 crashes.
[Enigma2_crash_2018-08-09_13-57-22.log](https://github.com/OpenViX/enigma2/files/2274264/Enigma2_crash_2018-08-09_13-57-22.log)
This seems to have something to do with a late modification to PLi, as the same version gives the same crash on PLi release (but not on recent PLi dev).

**Comment by Huevos** [comment]
No idea which repo that plugin is on.

**Comment by RobvanderDoes** [comment]
OE-A builds the plugin from the original source which is @ https://github.com/ims21/MovieManager

**Comment by Huevos** [comment]
https://github.com/ims21/MovieManager/pull/5/commits/f30a88a8bd1ee2864cda10c68bcd891f1894089b

**Comment by RobvanderDoes** [comment]
Thanks, that works fine.
Let's hope it will be accepted.

**Comment by RobvanderDoes** [comment]
Merged so closed as fixed.
