### ISSUE TITLE
RemainingToText enum typo

### ISSUE THREAD

**Issue by SimonCapewell** [OpenViX/enigma2#299]
`WITH_SECONDS` looks to have the wrong constant value. I suspect it should have a value of 1.

```
class RemainingToText(Poll, Converter, object):
	DEFAULT = 0
	WITH_SECONDS = 2
	NO_SECONDS = 2
```

**Comment by RobvanderDoes** [comment]
Closed as fixed by  https://github.com/OpenViX/enigma2/commit/00e41715b4827c09a9a33ea956ed3d0129b66662
