### ISSUE TITLE
crash timedateinput [EPGSelection] branch Dev 

### ISSUE THREAD

**Issue by norhap** [OpenViX/enigma2#350]
[Enigma2_crash_2018-12-10_23-47-17.log](https://github.com/OpenViX/enigma2/files/2665271/Enigma2_crash_2018-12-10_23-47-17.log)
GraphicalEPG->key TEXT

branch Dev

**Comment by AbuBaniaz** [comment]
I can confirm the crash. Is there a reason you are not using the forum?

**Comment by SimonCapewell** [comment]
Even if you do get past the crash, it doesn't move the selection! Should be an easy fix.

**Comment by norhap** [comment]
hi AbuBania,
I thought that here the error would be detected before, Next time I will use the forum.

**Comment by AbuBaniaz** [comment]
Suppose if you are using a Dev build/files and not on beta team or using slack group, here will do.

@SimonCapewell 
Any progress on the fix?

**Comment by SimonCapewell** [comment]
Yeah, on the way. I'm mixed up in other tweaks though!

**Comment by AbuBaniaz** [comment]
Many thanks for the fix @SimonCapewell 
https://github.com/OpenViX/enigma2/commit/0d142151397737823e95929df1ead54ca8e52127
