### ISSUE TITLE
"Accented" characters show incorrectly in OpenWebIF interface

### ISSUE THREAD

**Issue by original-birdman** [OpenViX/enigma2#375]
_e.g,_ "Les Misérables" shows OK in the on-screen EPG, and AutoTimers for it work.
However, viewing the channel EPG in `OpenwebIF` displays:

   Les MisÂerables

as does an xml file dump using `.../web/epgservice?sRef=1:0:1:104D:104D:233A:EEEE0000:0:0:0&time=1548622800'`
That Â is U+00c2 (so the bytes for Âe are 0xc3 0x82 0x65).
This is how `epgcache.lookupEvent()` is returning the data. Looks like a double-encoding of some sort? Or just plain mis-encoding?
Although `OpenWebIF` _shows_ the problem, it is _caused_ by the way the `enigma2` is returning the data.

**Comment by AbuBaniaz** [comment]
Are other images OK, i.e issue specific to ViX?

If it is an OpenWebIF issue, might be better to raise the issue here
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif

**Comment by original-birdman** [comment]
It's _not_ an OpenWebIF issue. Hence the two final sentences of my original post.

As for other images, I can't comment as I've never run any.
