### ISSUE TITLE
new frequencies for DVB-T/T2 in Spain

### ISSUE THREAD

**Issue by chrpinedo** [OpenViX/enigma2#483]
I recently lost some channels of my DVB-T2 tunner. My DVB-T2 tunner was configured to be located in Spain. When I select region Europe, I was able to tune again the lost channels.

So it seems that the frequency range for DVB-T/T2 in Spain is outdated.

**Comment by Huevos** [comment]
Thanks for your report. Please report this on the correct repo with full details of the changes needed. Only you know what mast and frequencies are available in your area. Also please post a link to the official website that shows the frequency allocation for your area.

The correct repo for posting issues with terrestrial.xml is here...
https://github.com/oe-alliance/oe-alliance-tuxbox-common/tree/master/src

**Comment by chrpinedo** [comment]
I did a pull request to the suggested repo https://github.com/oe-alliance/oe-alliance-tuxbox-common/pull/86
Thanks!
