### ISSUE TITLE
[Language] language.py "issue = bug" initial wizard

### ISSUE THREAD

**Issue by nunigaia** [OpenViX/enigma2#506]
The file "language.py" file has an issue.

Initial wizard ( start wizard screens ( video mode > network initial wizard > Initial wizard tuner settings >etc ...  ) 

Language wizard has 44 languages defined at python code, although from initial wizard ( start wizard ) is only possible to select from them 24. It seems there is anything at python code that is breaking the usage of the choosing from the 44 languages defined at python code.

Translations are not applied at initial wizard as per example: PT, PT-BR etc, if the users intend to change via the RED BUTTON the initial language ( at the first initial settings ( boot ), or after a factory reset.

Hope that can be fixed, as i have tested at OpenBlackHole 4.3.018 with language.py file from OpenATV ... and i can set from the beginning the PT language as others on the list.

best regards
nunigaia

**Comment by nunigaia** [comment]
As complement: The issue is at OpenVIX 5.30.18 also and previous versions from a long time .... and is the same :(

**Comment by IanSav** [comment]
I have completely refactored and rewritten the entire Language system for Enigma2.  The new code is being reviewed at the moment.  When the code review is complete I will be updating OpenATV, OpenPLi and OpenViX with the new code.

**Comment by nunigaia** [comment]
Ok, Thanks ... if you want, send me file in order to test it at BlackHole team ( Open BlackHole ). I can ask 
other members to test it, and report here any issue.

best regards
nunigaia
