### ISSUE TITLE
Confirmation of Deletion Message 1

### ISSUE THREAD

**Issue by EMJB** [OpenViX/enigma2#60]
When a directory is being deleted, the request for confirmation lists the number of files. To someone unfamiliar with the detailed workings this is confusing as there are several, but not a fixed number, of files per recording. I suggest:

(1) Line 2106 "files += 1" is replaced by:
"if ffn.endswith(".ts"):								# New condition to only count recordings 	files += 1"

(2) In the 	message box call on line 2109, "file(s)" is replaced by "recordings"

so as not to confuse the less technically aware.

**Comment by AbuBaniaz** [comment]
Which file please?

**Comment by EMJB** [comment]
Oops, sorry I thought the issue was specific to the file - MovieSelection.py.

EMJB

**Comment by rossi2000** [comment]
yo

1.  fixed. https://github.com/OpenViX/enigma2/commit/3dbe91df2e74d3bd4f434e8b69b7d34a6fa9226a

2. we cannot change files to recordings as a lot of people tend to have more than just recordings going on, in the HDDs. me for e.g.:,  I have recordings, mkv movies and mp3s/wavs
