### ISSUE TITLE
Confirmation of Deletion Message 2

### ISSUE THREAD

**Issue by EMJB** [OpenViX/enigma2#61]
When I delete a directory "X" containing  Y files but no lower level directory, the confirmation message says 'X' contains Y files and 1 sub-directory", which is incorrect as it contains no sub-directory. I think that all is needed is the removal of the line "subdirs += 1" at line 2083.

**Comment by EMJB** [comment]
This refers to MovieSelection.py

**Comment by AbuBaniaz** [comment]
That line was added to allow for the deletion of empty folders. We'll need to look at it further.

**Comment by EMJB** [comment]
Sorry - missed that problem. Can't you just replace "subdirs" with "subdirs-1" in the subsequent "are you sure" message?

**Comment by rossi2000** [comment]
fixed, cheers!

https://github.com/OpenViX/enigma2/commit/49ecffb4f32663c2537c58c8573bb9ca072d6a65
