### ISSUE TITLE
Minor Nitpick - "Directory" or "Folder" in User Messages

### ISSUE THREAD

**Issue by EMJB** [OpenViX/enigma2#62]
I note that many of the references to "folder" in user messages present around April 2016 have been replaced by "directory", but 3 remain @ lines 253, 255, & 262, all in the configuration area. I appreciate that:

(1) Most people with a computer background consider the two terms as interchangeable, but to others it can be very confusing.

(2) Being in the configuration area, they are less likely to be met  by those without computer experience.

but it would be nice to change these at the next update if there are no problems I have not foreseen.

EMJB

**Comment by EMJB** [comment]
This refers to MovieSelection.py.

**Comment by rossi2000** [comment]
fixed in next builds after I commit the changes, thanks.
