### ISSUE TITLE
groupedservices doesn't display channel names

### ISSUE THREAD

**Issue by jeepcook** [OpenViX/enigma2#634]
Hello,

Concerned github repository enigma2/data.

When the groupedservices file is correctly set, if you select a channel list in, you can display all sub channels defined in the groupedservices file by pressing green button.

But the only displayed information is the current epg for every sub channel. So if you have the same sub channel but with different versions, we are unable to know which one to select, because they have the same now epg, and no name. Same thing if you have a lot of distinct channels, because the channel name is not displayed you are unable to choice (example with the HD+ bouquet set in the default groupedservices file).

I think the solution could be to display "channel Name | now epg". For the channel name, the better solution could be to display the name of the channel set in the groupedservices files:

Example: for 2 french channels, their names are the same in lamedb (One is TF1, the second one FRANCE 2), so displaying the channel name extract from lamedb is not a solution because they are the same. But displaying the channel name set after the # could be great.
TF1

1:0:19:2460:440:1:C00000:0:0:0: #TF1 CSAT
1:0:19:601:6:20FA:DDE0000:0:0:0: #TF1 PLS TNT
1:0:19:191:4FB0:55F:DDE0000:0:0:0: #TF1 FRANSAT
FRANCE 2

1:0:19:245A:440:1:C00000:0:0:0: #FRANCE 2 CSAT
1:0:1:101:1:20FA:DDE0000:0:0:0: #FRANCE 2 PLS TNT
1:0:19:12D:4F4C:55F:DDE0000:0:0:0: #FRANCE 2 FRANSAT
.......

If you need some other informations, please contact me.

Thanks

**Comment by Huevos** [comment]
Please can you provide a step by step guide of what you want done.

**Comment by jeepcook** [comment]
Ok.

1:
For openvix, the config file is /usr/share/enigma2/groupedservices (but I think it can be under /etc/enigma2), to enable it you have to attribute in button setup green button to Infobar/show subservice selection

2:
Example for these channels set in default groupedservices file:
# HD Plus
1:0:19:EF74:3F9:1:C00000:0:0:0: #Sat1 HD
1:0:19:EF10:421:1:C00000:0:0:0: #RTL HD
1:0:19:EF15:421:1:C00000:0:0:0: #RTL2 HD
1:0:19:2E9B:411:1:C00000:0:0:0: #Super RTL HD
1:0:19:EF76:3F9:1:C00000:0:0:0: #kabel eins HD
1:0:19:EF11:421:1:C00000:0:0:0: #Vox HD
1:0:19:EF75:3F9:1:C00000:0:0:0: #ProSieben HD
1:0:19:EF78:3F9:1:C00000:0:0:0: #ProSieben MAXX HD
1:0:19:151A:455:1:C00000:0:0:0: #DMAX HD
1:0:19:5274:41D:1:C00000:0:0:0: #Welt HD
1:0:19:1519:455:1:C00000:0:0:0: #TELE 5 HD
1:0:19:EF14:421:1:C00000:0:0:0: #n-tv HD
1:0:19:1581:41F:1:C00000:0:0:0: #Sport1 HD
1:0:19:5273:41D:1:C00000:0:0:0: #Nick/MTV+ HD
1:0:19:EF77:3F9:1:C00000:0:0:0: #sixx HD
1:0:19:157F:41F:1:C00000:0:0:0: #DELUXE MUSIC HD
1:0:19:2777:409:1:C00000:0:0:0: #MTV HD
1:0:19:2EAF:411:1:C00000:0:0:0: #RTL Nitro HD
1:0:19:30D4:413:1:C00000:0:0:0: #SAT.1 Gold HD
1:0:19:2774:409:1:C00000:0:0:0: #TLC HD
1:0:19:157C:41F:1:C00000:0:0:0: #Disney Channel HD
1:0:19:1392:3EA:1:C00000:0:0:0: #INSIGHT TV HD
1:0:1F:2:40B:1:C00000:0:0:0: #UHD1 by Astra HD
1:0:1F:183A:40B:1:C00000:0:0:0: #Travelxp 4k
1:0:1F:307A:3F5:1:C00000:0:0:0: #RTL UHD

--> zap to one of these channels, touch green (channel must have epg) and a list of subservices will be showned. But you will see only epg for each channel but not the name of the channel. 

To be more complete, the channel name should be the name after "ServiceReference #", by this way if you have more than one channel with the same name in lamedb, you will be able to do the difference between channels (case for regional channels for example).

I hope my description is clear.

Thanks.

Regards

**Comment by RobvanderDoes** [comment]
Thanks, your description is clear and the issue is clear as well.

**Comment by jeepcook** [comment]
Hello,
I did some search and I think modification has to be made into enigma2 repository under /lib/python/Screens/InfoBarGenerics.py
Just for your information, this bug exists in every oe-alliance team images, but each has its own enigma2 repository.
Regards.

**Comment by jeepcook** [comment]
Hello,

I think the groupedservices functionality has to be removed from enigma2 repositories (for all oe-alliance builds) to be transferred to oe-alliance-core repository.
It's a common functionality so updates has to be committed in oe-alliance instead of to be done on each builds. In fact, using the same way to do as for example tuxbox-common is.
What do you think about?
Thanks

**Comment by RobvanderDoes** [comment]
The issue has now been fixed.

**Comment by jeepcook** [comment]
Hello, thanks for the fix. The fix is for every oe-alliance images ?

**Comment by RobvanderDoes** [comment]
No: it's in E2, so only for ViX.

**Comment by Huevos** [comment]
> Hello, thanks for the fix. The fix is for every oe-alliance images ?

Each team has its own enigma and each team decides how to configure it. This is not something that can be applied in common. If other teams are interested they can cherry-pick the commit.
