### ISSUE TITLE
Autotimer

### ISSUE THREAD

**Issue by jbleyel** [OpenViX/enigma2#695]
Can we delete this? -> 
https://github.com/oe-alliance/enigma2-plugins/tree/master/vixautotimer

**Comment by TwolDE2** [comment]
In the build openvix-enigma2.bb specifies as a req : enigma2-plugin-extensions-autotimer \ so not sure where else ViXautotimer could be included

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/enigma2-plugins/commit/9f51896e1eb508d27a3a66fa599adc076c1ad0fb

**Comment by jbleyel** [comment]
And Revert.
https://github.com/oe-alliance/enigma2-plugins/commit/65768f59d5026162ba65e217ea9c4bdf188fb5c1#diff-0462e381b2fb3286568215681c8983490a37ac9ae0f0c5ee304df7fa6426d4af

**Comment by jbleyel** [comment]
I think we can remove it.

**Comment by TwolDE2** [comment]
Let me post in the ViX forum and see if we can get a consolidated view - I notice that there are python3 branches for both plugins - have they also been merged into Master or are there 2 different branches of each plugin?

**Comment by TwolDE2** [comment]
I have also just checked and run a comparison on my python3 ViX image and the installed autotimer plugin is using Autotimer not ViXautotimer..... and I have been running quite happily for the last "x" months without noticeable issues.

**Comment by TwolDE2** [comment]
Just read again the revert post ... so cannot see why not remove, just additional work to keep it.

**Comment by jbleyel** [comment]
It's gone. ;-)
