### ISSUE TITLE
list.py def getIndex(self) needs to return 0, not None

### ISSUE THREAD

**Issue by kiddac** [OpenViX/enigma2#697]
The function 

	def getIndex(self):
		return self.master.index if self.master is not None else None
		
		
needs to return 0, and not None.

In python 3 you cannot perform arithmetic on None. 

i.e

if self.getIndex() + 1

**Comment by Huevos** [comment]
No, it can't return zero because zero is an index, and the list may be zero length.

**Comment by Huevos** [comment]
Also, you need to look at why certain code does not set self,master correctly.

**Comment by Huevos** [comment]
And by the way you can't perform arithmetic on "None" in Py2 either. e.g. as per your example `self.getIndex() + 1`

```
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> None + 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
>>>
```

**Comment by kiddac** [comment]
Nobody writes perfect code. 
As highlighted in my plugin where updatelist was called before a setlist. 
If this value would have been 0 and not None (like other image teams are changing it to), then the updatelist wouldn't have failed and continued to function.
Yes I understand the crash highlighted a minor error in my code, but its an error that could have been skipped.

**Comment by Huevos** [comment]
0 is the index of the first item in the list. So returning 0 is wrong as a list can be zero length.

You need to look at why self.master is not being set.

I am aware of that arithmetic problem which could be protected by a sanity test. 

But returning 0 as the index when none is available is not the way forward in my opinion.

Twol reports a similar problem with xstreamity.

**Comment by Huevos** [comment]
```

Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> myList = []
>>>
>>> myList[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>>
>>>
```
