### ISSUE TITLE
Bug EventView Panel

### ISSUE THREAD

**Issue by nunigaia** [OpenViX/enigma2#713]
1)   Add a Timer using EventView panel ( Press EPG )

2)   After adding it ... on the same panel you are able to delete or edit timer, by pressing the blue button

3)   Delete timer > OK button ... no issue

Pressing GREEN button to delete, then GREEN ( opens the SINGLE EPG PANEL ), then GREEN to save ... it will gives the BSOD.

It happens on Master and Python3 ( DEV image ), tested on a DUO4K SE, DUO4K, ULIMO4K!

**Comment by Huevos** [comment]
Thanks for reporting.

**Comment by nunigaia** [comment]
No problem, Thanks @huevos

**Comment by RobvanderDoes** [comment]
I can't reproduce this atm; maybe it has been fixed already?

**Comment by RobvanderDoes** [comment]
I take it this has been fixed
