### ISSUE TITLE
config.hdmicec.fixed_physical_address is ignored/no longer works

### ISSUE THREAD

**Issue by andatche** [OpenViX/enigma2#746]
For HDMI input switching to work correctly with my TV/STB combo (a Hisense A7200G and Vu+ Solo2) I have to manually configure the CEC physical address using the `config.hdmicec.fixed_physical_address` option. If I don't, input switching doesn't work.

Since OpenViX 6.0.006 this isn't working anymore. It looks like the option is ignored since some refactoring in 041bafc2.

**Comment by TwolDE2** [comment]
Can you raise on the OpenViX forum and  post the debug log?
Need to understand why the CEC physical address is not picked up automatically and what address you manually switch to….

**Comment by andatche** [comment]
Sure, will do! :)

I have to manually configure the address as x.0.0.0, where x is the relevant HDMI input on the TV.

**Comment by andatche** [comment]
@TwolDE2 thanks for taking the time to restore the ability to manually configure the CEC physical address (c398de5a). I can confirm this has resolved my issue in OpenViX 6.0.007.

Unfortunately I haven't had time to collect debug logs to figure out why the STB isn't getting the correct address in the first place, but will do so when time permits.
