### ISSUE TITLE
Crash when FF recorded stream files on build 6.2 (Dev)

### ISSUE THREAD

**Issue by lincsat** [OpenViX/enigma2#768]
I have files recorded from IPTV using service ref 4097 which are recorded as .stream files. When playing these with the inbuilt player the box crashes if I FF or REW or use the jump forward or backwards number buttons. If I rename the .stream to .ts then it's fine. Just when the file has the .stream suffix. I have tried ATV 7.1 and the fault is not present in that.

`<   236.3871> [InfoBarGenerics] Key: 4 (Make) KeyID='KEY_3' Binding='('3',)'.
<   236.4924> PC: b5dadae0
<   236.4926> Fault Address: 00000000
<   236.4928> Error Code: 0
<   236.4932> Backtrace:
<   236.4936> /usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x7B678]
<   236.4939> /lib/libc.so.6(__default_rt_sa_restorer) [0xB5D74D30]
<   236.4942> /lib/libc.so.6(n/a) [0xB5DADAE0]
<   236.4945> /lib/libc.so.6(raise) [0xB5D73EE0]
<   236.4947> /lib/libc.so.6(abort) [0xB5D61638]
<   236.4949> -------FATAL SIGNAL (6)
`

**Comment by ccs-ccs** [comment]
Discussed here...  https://www.world-of-satellite.com/showthread.php?65193-Problem-with-file-player

**Comment by lincsat** [comment]
I've now built 6.2.001.009 with the Ubuntu 22.04LTE and it's stepping forward and backwards OK, so that bug is fixed.
