### ISSUE TITLE
Website link issue (picons.eu no longer as it was)

### ISSUE THREAD

**Issue by wedebe** [OpenViX/enigma2#771]
I don't fancy registering on yet another forum just to report this, so hopefully someone has direct contact with the webpage manager of openvix.co.uk

The picons.eu domain now redirects to a sex-based domain address, so I'd suggest any and all links to it are removed or changed.

https://www.openvix.co.uk/index.php/downloads/picons-channel-icons/ocram-srp-picons-service-reference-named-picons/

**Comment by wedebe** [comment]
(This also calls into question the security of externally-hosted ipk files. If the new site owners knew how, they could create and serve a malware ipk).

**Comment by Huevos** [comment]
Thanks for reporting. If you need picons download them from the feeds.
