### ISSUE TITLE
CamoFs instalation problem with python3.10

### ISSUE THREAD

**Issue by txz-pt** [OpenViX/enigma2#780]
I was trying to install CamoFS, with ipkg vix install via FTP.

I have a the latest openvix6 image in Vu Uno4k, but i can´t install because are problems with dependencies. The instalation can´t find python-imaging and python-subprocess. I think this has to do with the old structure of the program. I think he is trying to find the python structure before 3 versions. I found an image.pyc in file /usr/lib/python3.10/site-packages/PIL and subprocess.pyc in file /usr/lib/python3.10 . Are this the right files? Where can i put them in a old strucuture of python?

**Comment by RobvanderDoes** [comment]
CamoFS is a "closed source" plugin, so there's not much we can do.
Best ask the author for help.

**Comment by Huevos** [comment]
You can't run a Python 2 plugin on a Python 3 image. It will need converting.
