### ISSUE TITLE
Cannot set recording or timeshift to NFS partition

### ISSUE THREAD

**Issue by chulann** [OpenViX/enigma2#799]
Hi,
I'm getting an error "partition must be ext or nfs" error when trying to set Recording or Timeshift partition on OpenVix 6 2 010 on my Formuler F1 box.

I'm trying to save to a mounted ZFS partition - I've had to mount using nfsvers=4 option in /etc/fstab so I can get at all my datasets.

I have edited Recordings.py and Timeshift.py to explicitly add 'nfs4' to the supported_filesystems. 

I tweaked the isValidPartition function as part of Timeshift.py (additions in bold):

			for partition in Components.Harddisk.harddiskmanager.getMountedPartitions():
				**print("[Timeshift] DEBUG: mountpoint %s and filesystem %s" % (partition.mountpoint, partition.filesystem()))
				print("Valid", partition.filesystem() in supported_filesystems)**
				if partition.filesystem() in supported_filesystems:

Results I got as I was cycling through the various partitions was:
<   210.0182> [Timeshift] DEBUG: path /beast/, mountpoint / and filesystem ubifs
<   210.0202> Valid False
<   221.3488> [Timeshift] DEBUG: path /media/, mountpoint / and filesystem ubifs
<   221.3506> Valid False
<   224.8464> [Timeshift] DEBUG: path /e2/timeshift/, mountpoint / and filesystem ubifs
<   224.8483> Valid False
<   228.7765> [Timeshift] DEBUG: path /beast/enigma2/timeshift/, mountpoint / and filesystem ubifs
<   228.7786> Valid False

I think it's that getMountedPartitions in Harddisk.py is not picking up my NFS partition but my Python foo isn't strong enough to figure out exactly what's going on. 

I've upgraded to 011 (via GUI update) but problem persists

**Comment by TwolDE2** [comment]
Open a thread on https://www.world-of-satellite.com/
Posting here is not the way to have a conversation

**Comment by chulann** [comment]
To be fair, it's an issue with the code, so it does belong here I believe.
I just don't have the experience to identify exactly where it is. The
detail in the bug report is intended to explain the issue, say what
investigations and attempted solutions were made

Also, it has been posted on the forum and I haven't got enough help or
progress: last page of
https://www.world-of-satellite.com/showthread.php?64862-Cannot-move-up-and-down-in-a-Setup-screen/page8

It worked in version 5, it's broken in version 6 and I can't figure it out.
It dramatically reduces the functionality of OpenVix for me

Regards,
Cian

**Comment by TwolDE2** [comment]
So you are using a zfs partition- if you want us to resolve this situation then post on the forum…. I have had covid for 2 weeks and now in South Africa on holiday - don‘t assume you are the only person with issues
I wil close this on Git

**Comment by chulann** [comment]
I'm using an *NFS mounted* ZFS partition. The fact that it's ZFS is
irrelevant in terms of enigma2 as far I can see (happy to be corrected) -
it was given as context as to why I need an nfs4 mount rather than nfs (and
trying to give as much information to assist any developer who was good
enough to review).

I am sorry you have COVID and do genuinely hope you feel better. However,
no software engineer in the world can assist you with that.

The simple fact is that it's a bug, which reduces the intended and
advertised functionality of the software (again, it worked perfectly fine
in 5). If you refuse to recognise that, there is obviously nothing I can
do. It is really disappointing that you will refuse to even acknowledge
there is an issue and shoot the messenger instead. It goes entirely against
the ideals of open source software.

**Comment by TwolDE2** [comment]
I will post some added debug in the Forum  thread when I get back (probably Friday) - nobody is ignoring, but posts stopped at end of September … in fact I think mine was last post.
So lets see if we can find the issue - the code was changed to ensure that all Timeshares requirements were met

**Comment by Huevos** [comment]
> The simple fact is that it's a bug, which reduces the intended and advertised functionality of the software
>

What advertised functionality? Please provide a link.
