### ISSUE TITLE
Building problems

### ISSUE THREAD

**Issue by jdauthre** [OpenViX/enigma2#824]
I am not very familiar with linux, but am having difficulty in building openvix.  All was reasonably okay until:
openvixbuilder@ubuntu:~/openvix/build-enviroment$ MACHINE=vuultimo4k DISTRO=openvix DISTRO_TYPE=release make image
check internet connection: Online      
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  lz4c
make: *** [Makefile:1101: image] Error 1

I then tried to install Iz4c:
openvixbuilder@ubuntu:~/openvix/build-enviroment$ sudo apt-get lz4c
[sudo] password for openvixbuilder: 
openvixbuilder is not in the sudoers file.  This incident will be reported.

So I am now stuck!
Thanks in advance

**Comment by Huevos** [comment]
Check user IS in /etc/sudoers and that file has 0440 permissions.

**Comment by jdauthre** [comment]
Thanks, no it is not in sudoers file.  What do I have to enter into the file, and how do I check / change the file permissions?

**Comment by AbuBaniaz** [comment]
I hope you can solve the issue. Would have been easier if you skipped the create user steps in the guide/readme.

**Comment by jdauthre** [comment]
you might well be right!

**Comment by AbuBaniaz** [comment]
Did you clone 5.1 or 5.2 branch?

**Comment by jdauthre** [comment]
If you mean  oe-alliance-core  it was 5.1. The openvix/enigma2 branch was the default developer branch.

**Comment by AbuBaniaz** [comment]
For info, maybe not directly related to the issue you are having: We are using 5.2 branch for current image. I submitted a pull request to correct that in the readme.

**Comment by Huevos** [comment]
The reason for the user is so the build can't interfere with files outside its scope.

**Comment by jdauthre** [comment]
> The reason for the user is so the build can't interfere with files outside its scope.

That makes sense . Thanks
