### ISSUE TITLE
Recording player has lost most codecs

### ISSUE THREAD

**Issue by ahlstart** [OpenViX/enigma2#868]
In OpenVix 6.2.002-20221009-0033 the media files (.mkv) on my NAS drive played back just fine.
Now, in OpenVix 6.3.007-20230426-2106 all I get from anything (tried .webm, .m4v H.264 & H.265, .mov, .mp4) other than .ts files, is a fancy static image containing lots of slanted rectangles.
Please bring back the ability to successfully play back also other media files than recordings (.ts files) as my smart TV (and BluRay player) is deliberately not so smart as to browse to a NAS share and play media files.

**Comment by TwolDE2** [comment]
Please post in forum here
https://www.world-of-satellite.com/forum.php

**Comment by ahlstart** [comment]
Forum thread 65863 , reply #7, contained the trick to get rid of the symptom: The setting "new GStreamer playback" must be = no.
Maybe this setting needs a bit more work; either in warning users about tinkering with it or - preferably - by adding the ability to fall back to old functionality upon unexpected results (it does not error out, just does not display video, so noticing anomalies may be tricky).

I leave the decision about closing this issue to you.
