### ISSUE TITLE
Unable to add directories to backupdirs

### ISSUE THREAD

**Issue by pbloigu** [OpenViX/enigma2#915]
Adding additional directories to config.backupmanager.backupdirs in /etc/enigma2/settings doesn't seem to have effect. The added directory is not backed up and thus not restored either after system update. Also, the value of config.backupmanager.backupdirs is reverted to the value it was before the update.

**Comment by TwolDE2** [comment]
So Yellow key (Select/Deselect) followed by Green key (Save) doesn,t work for you??

**Comment by pbloigu** [comment]
> So Yellow key (Select/Deselect) followed by Green key (Save) doesn,t work for you??

There's an UI for doing that? I wasn't aware... I just went and manually edited /etc/enigma2/settings file. But if it isn't even supposed to work like that.... I guess I need to do my homework and try and find the UI for making that change.

**Comment by TwolDE2** [comment]
Blue key, Vix, Backupmanager, menu key then add files, directories

**Comment by pbloigu** [comment]
> Blue key, Vix, Backupmanager, menu key then add files, directories

Ok, found it, and it works, thanks! 

I guess I managed to hit one of those rare cases where command line is NOT king. Anyway, my apologies for not doing my homework on this one. 

Please, consider this issue resolved, and again, thanks!
