### ISSUE TITLE
There is no signal on the following frequencies

### ISSUE THREAD

**Issue by atefganm** [OpenViX/enigma2#941]
There is no signal on the following frequencies

![Screenshot from 2023-11-27 16-22-35](https://github.com/OpenViX/enigma2/assets/31848885/3e168ecd-0bf3-47c9-822f-2fa773c347ed)

After recent commitments

![Screenshot from 2023-11-27 16-20-25](https://github.com/OpenViX/enigma2/assets/31848885/bfef07b1-57e4-4853-97ef-69acfc79d944)

**Comment by TwolDE2** [comment]
What box, what tuners? Maybe post on WoS forum.

**Comment by atefganm** [comment]
dm 820

![1](https://github.com/OpenViX/enigma2/assets/31848885/34c49005-ab4e-4ab6-8118-920767e54010)

![2](https://github.com/OpenViX/enigma2/assets/31848885/66373d1e-ece2-43c1-8876-437b8d6ed85e)

**Comment by TwolDE2** [comment]
Try different time delay….
https://github.com/OpenViX/enigma2/commit/403732e75635eab3134c364a97c01a45d3086259

**Comment by Huevos** [comment]
No problem tuning those transponders here.

![1](https://github.com/OpenViX/enigma2/assets/2067864/1b33063a-517b-42e0-a834-96101965cb40)

![2](https://github.com/OpenViX/enigma2/assets/2067864/9bbe336d-4b09-48f1-bbdc-c030a23af196)

**Comment by atefganm** [comment]
Usually signal frequencies
After this commitment
https://github.com/OpenViX/enigma2/commit/5052871b76586962940a68c35b0760c9ca7d131e
------------------------
Thanks @TwolDE2
He thanked @Huevos
Also thanks to @Ev0-BH

![3](https://github.com/OpenViX/enigma2/assets/31848885/015cc98f-4ec1-47af-91ca-1e952b100c08)

![4](https://github.com/OpenViX/enigma2/assets/31848885/1ed16313-8fa4-49eb-850c-27d45b0f6bf2)

**Comment by TwolDE2** [comment]
So you have signal but cannot access sr services?

**Comment by atefganm** [comment]
There is no problem now after the commitment referred to in
My previous response, the channels are working fine

![1_0_19_74_3_85_C00000_0_0_0_20231128225644](https://github.com/OpenViX/enigma2/assets/31848885/09ae511f-e480-4e79-91e5-7d9dec0a06e8)
![1_0_19_74_3_85_C00000_0_0_0_20231128225739](https://github.com/OpenViX/enigma2/assets/31848885/164dd284-0ec1-47f9-93e0-5d9e9d5a5308)
![1_0_19_206_2_85_C00000_0_0_0_20231128230103](https://github.com/OpenViX/enigma2/assets/31848885/9c4c52c9-6790-4419-bf82-e990d396234a)
