### ISSUE TITLE
Vu+ zero4k snr check

### ISSUE THREAD

**Issue by sys2065** [OpenViX/enigma2#960]
frontend.cpp has following code:

<code>else if (!strcmp(m_description, "Vuplus DVB-S NIM(Si2166)")) // VU+ Zero4K
	{
		ret = snr;
	}</code>

That won't work, because correct id is "Vuplus DVB-S NIM(SI2166)" and strcmp is case sensitive.

![vuzero4k_tuner_id](https://github.com/OpenViX/enigma2/assets/127239734/f0dc810f-5d45-4da9-9a39-cd24e4ed79a6)

Fix here: [zero4k_snr.txt](https://github.com/OpenViX/enigma2/files/13797442/zero4k_snr.txt)

**Comment by AbuBaniaz** [comment]
These changes have been added.
